default: &default
  password: "yWgU+WrUy75U4KxC+ZdwKlQV/YiuTDgBmeKsZGly+xL3s8Xfqm70JUgg9U/hNimyo8o/227XIVV6RbEG2mRRpqaJ/1ijiwJAHDOPFofewizZ8QufeciCVi59muOrglZ/J3xqjNhGO3SL8q3aum91Tw5xYASR/rNcLihpKepyhQdGhwPuszlbuZK9stHRZJKZLomMRsmT19/nY+jbDElI8yR3AjxygVE3zWmzrxc/z3QprIbVuYMXsbjtRtiBhwc372qjppL6ulDb8wVV96FJSXWjK9BKAQaI5XIclkxb2UEq6Dlq3lARMaUZvI+xk7mH4rQBLwqGX7xM34q9svmTYQ=="

development:
  <<: *default

production:
  <<: *default

test:
  password: "pass"